$(document).ready(function(){$('.row-btn .terminos').bind('click',function(e){e.preventDefault();var self=$('.bgExpoistor.terminos_condiciones');if(self.hasClass('bgExpoistor terminos_condiciones none')){self.fadeIn();}
$('.row-btn .terminos .wpcf7-checkbox input').prop('checked',true);});$('.slideBanner').slick({autoplay:true,autoplaySpeed:5000,speed:600,fade:false,arrows:false,dots:true});$('.profile').bind('click',function(e){e.preventDefault();var self=$(this).parent().next();if(self.hasClass('bgExpoistor none')){self.fadeIn();}});$('.closeProfile').bind('click',function(e){e.preventDefault();$(this).parent().parent().fadeOut();});$(".main__slider").slick({centerMode:true,autoplaySpeed:4000,infinite:true,autoplay:true,slidesToShow:3,slidesToScroll:1,arrows:false,initialSlide:2,responsive:[{breakpoint:1000,settings:{slidesToShow:1,fade:true}}]});$('.misha_loadmore').click(function(){var button=$(this),data={'action':'loadmore','query':misha_loadmore_params.posts,'page':misha_loadmore_params.current_page};$.ajax({url:misha_loadmore_params.ajaxurl,data:data,type:'POST',beforeSend:function(xhr){button.text('Loading...');},success:function(data){if(data){button.text('More posts').prev().before(data);misha_loadmore_params.current_page++;if(misha_loadmore_params.current_page==misha_loadmore_params.max_page)
button.remove();}else{button.remove();}}});});if($('.padd_taller_docentes .docente').length>1){$('.padd_taller_docentes').slick({autoplay:false,autoplaySpeed:8000,speed:400,fade:false,arrows:false,dots:false,slidesToShow:2,slidesToScroll:1,responsive:[{breakpoint:800,settings:{slidesToShow:1,}}]});}
if($('.bxslidClientes')){$('.bxslidClientes').slick({autoplay:true,autoplaySpeed:2500,speed:400,fade:false,arrows:false,dots:false,slidesToShow:5,slidesToScroll:1,responsive:[{breakpoint:1250,settings:{slidesToShow:3,}},{breakpoint:600,settings:{slidesToShow:2,}},{breakpoint:480,settings:{slidesToShow:1,}}]});}
if($('.ask-certificaciones .left li').length>1){$('.ask-certificaciones .left ul').slick({autoplay:true,autoplaySpeed:5000,speed:600,fade:false,arrows:false,dots:true});}
$('.slide').bxSlider({speed:1800,moveSlides:1});Shadowbox.init();(function(){var ev=new jQuery.Event('style'),orig=jQuery.fn.css;jQuery.fn.css=function(){jQuery(this).trigger(ev);return orig.apply(this,arguments);}})();setTimeout(function(){jQuery('img.ajax-loader').bind('style',function(e){var style=jQuery(this).attr('style');if(style){var text=jQuery(this).parent().find('input.wpcf7-submit').val();if(style.indexOf("hidden")>1){jQuery(this).parent().find('input.wpcf7-submit').attr('disabled','disabled');jQuery(this).parent().find('input.wpcf7-submit').css({'background':'#929292'});jQuery(this).parent().find('input.wpcf7-submit').hover({'background':'#929292'});}else{jQuery(this).parent().find('input.wpcf7-submit').prop('disabled',false);jQuery(this).parent().find('input.wpcf7-submit').css({'background':'#80b719'});jQuery(this).parent().find('input.wpcf7-submit').hover({'background':'#74a517'});}}});},2500)
$('.btn-responsive a').bind('click',function(e){e.preventDefault();$("header section .menu-top").fadeIn(300);});$('.responsiveLogo .close').bind('click',function(e){e.preventDefault();$("header section .menu-top").fadeOut(300);});$('header section nav .menu li').each(function(){$(this).find("a").append('<span class="indicator"><img src="'+template_url+'/wp-content/themes/seminarios/images/down.png"></span>')});if($('.title_style, .title, .title_white').length>0){}
if($('.content .bxslider').length>0){MyApp.bxslider.init();}
if($('.scroll-pane').length>0){MyApp.scrollpane.init();}
if($('.files').length>0){MyApp.selectmenu.init();}
if($('.nav').length>0){MyApp.menu.init();}
if($('.clower').length>0){MyApp.clock.init();}
if($('.datepicker').length>0){MyApp.date.init();}
if($('#countdown_dashboard').length>0){MyApp.conteo.init();}
if($('.slide-header').length>0){MyApp.slide.init();}
if($('.content_exhi').length>0){MyApp.slide.init();}
if($('.toggleSpeed').length>0){MyApp.speed.init();}
if($('.leftSobreCurso').length>0){$(".leftSobreCurso").accordion({heightStyle:"content"});}
if($('.contentTemario').length>0){$(".contentTemario").accordion({heightStyle:"content"});}
if($('.verMasPost').length>0){MyApp.ajaxPost.init();MyApp.verMasCate.init();}
MyApp.fade_button.init();MyApp.up.init();MyApp.precarga();if($('.slideimg').length>0){MyApp.bxslider_seminarios.init();MyApp.bxslider_seminarios.cursos();}
if($('.gallerycontainer').length>0){MyApp.galeria.init();}
if($('.page-template-page-matricula').length>0){MyApp.matricula.init();}
MyApp.scrollMenu.init();});MyApp={precarga:function(){var inicio=new Date;function tiempo_carga(){var fin=new Date;var segundos=(fin-inicio)/1000;if(segundos<=segundos){setTimeout(function(){$('body').css('overflow','visible');$('body').css('overflow-x','hidden');$('.load').fadeOut(400);},500);};}
onload=function(){tiempo_carga();}},matricula:{html:function(i){var datos=$('.content-participantes').first().find('.datos-participantes').html();var html='<div class="content-participantes" attr="'+i+'"><div class="title"><div class="titledisplay"><i class="icon-docs"></i><span>Dato </span>Participante <span tipo="empresa" style="display: inline;">('+i+')</span></div></div><div class="datos-participantes">'+datos+'</div></div>';return html;},init:function(){$('.input-number').on('input',function(){this.value=this.value.replace(/[^0-9]/g,'');});$('.page-template-page-matricula .participantes a').on('click',function(e){e.preventDefault();var cant=$('.page-template-page-matricula .participantes input').val();var totalContent=$('.content-participantes').length;if(cant>1&&cant>totalContent){for(var i=totalContent;i<cant;i++){var newcant=i+1;var htmlParticipante=MyApp.matricula.html(newcant);$('.page-template-page-matricula .agregar-participantes').append(htmlParticipante);$('.content-participantes[attr='+newcant+'] input').val('');}}else if(cant>=1&&cant<totalContent){for(var i=totalContent;i>cant;i--){$('.content-participantes[attr='+i+']').remove();}}else{}});$('.page-template-page-matricula .row.label label').on('click',function(){if($(this).find('input[name=tipo]').val()=='Persona Natural'){$('.datos-participantes input').removeAttr('required');$('[tipo=empresa]').hide();$('[tipo=participantes]').val('1');$('.comprobante-pago.datos-participantes input').addClass('ignore').val('');if($('.content-participantes').length>1){$('.content-participantes').each(function(x){if(x>0){$('.content-participantes[attr='+x+']').remove();}});}}else{$('.page-template-page-matricula .participantes input').val('1');$('[tipo=empresa]').show();$('.datos-participantes input').attr('required');$('.comprobante-pago.datos-participantes input').removeClass('ignore');$('.input-number').on('input',function(){this.value=this.value.replace(/[^0-9]/g,'');});}});MyApp.matricula.validate();},validate:function(){$.validator.prototype.errorsFor=function(element){var name=this.idOrName(element);var elementParent=element.parentElement;return this.errors().filter(function(){return $(this).attr('for')==name&&$(this).parent().is(elementParent);});}
$.validator.prototype.checkForm=function(){this.prepareForm();for(var i=0,elements=(this.currentElements=this.elements());elements[i];i++){if(this.findByName(elements[i].name).length!==undefined&&this.findByName(elements[i].name).length>1){var seek=this.findByName(elements[i].name);for(var cnt=0;cnt<this.findByName(elements[i].name).length;cnt++){this.check(this.findByName(elements[i].name)[cnt]);}}else{this.check(elements[i]);}}
return this.valid();};$("#matricula-online").validate({ignore:".ignore",rules:{'nombre[]':"required",'apellidos[]':"required",'dni[]':'required','celular[]':'required','correo[]':{required:{depends:function(){$(this).val($.trim($(this).val()));return true;}},email:true},razon_social:"required",ruc:"required",direccion:"required",correo_factura:{required:{depends:function(){$(this).val($.trim($(this).val()));return true;}},email:true}},messages:{'nombre[]':"Requerido",'apellidos[]':"Requerido",'dni[]':"Requerido",'celular[]':"Requerido",'correo[]':{required:"Requerido",email:"Requerido"},razon_social:"Requerido",ruc:"Requerido",direccion:"Requerido",correo_factura:{required:"Requerido",email:"Requerido"},},errorPlacement:function(error,element){error.addClass("ui red pointing label transition");error.insertAfter(element);if($('.page-template-page-matricula .row.label label input[type=radio]').val()=='Empresa'){if(element.attr("name")=="razon_social"||element.attr("name")=="ruc"||element.attr("name")=="direccion"||element.attr("name")=="correo_factura"){error.removeClass}}},highlight:function(element,errorClass,validClass){$(element).addClass(errorClass);},unhighlight:function(element,errorClass,validClass){$(element).removeClass(errorClass);},submitHandler:function(form){MyApp.matricula.ajax();return false;}});},ajax:function(){var datos={action:'wpcf7Matricula',form:$('#matricula-online').serialize()};$.ajax({beforeSend:function(qXHR,settings){},complete:function(){},type:"post",url:template_url+'/wp-admin/admin-ajax.php',data:datos,success:function(response){if(response==1){window.location.replace('https://www.seminariostop.com/gracias/');}},error:function(error){console.log(error)}});}},scrollMenu:{init:function(){var altoHeader=$('header').height();$(window).scroll(function(event){var scrollAuto=$(window).scrollTop();var windowWidth=$(window).width();if(windowWidth>700){if(scrollAuto>altoHeader){$('#wrapper').addClass('fixed');}else{$('#wrapper').removeClass('fixed');}}});}},verMasCate:{init:function(){$('.verMasCate').on('click',function(e){e.preventDefault();if(!$(this).hasClass('active')){$cate=$(this).attr('values');$('.verMasCate').removeClass('active');$('input[name="categorias"]').val($cate);$(this).addClass('active');$('input[name="idPost[]"]').remove();$('.verMasPost').trigger('click');$('.listCourse ').html('');$('.verMasPost').fadeIn(300);}});}},ajaxPost:{init:function(){$('.verMasPost').on('click',function(e){e.preventDefault();var categorias=0;var postParent=0;var idPost=0;if($('input[name="categorias"]').length>0){var categorias=$('input[name="categorias"]').val();}
if($('input[name="postParent"]').length>0){var postParent=$('input[name="postParent"]').val();}
if($('input[name="idPost[]"]').length>0){var idPost=$('input[name="idPost[]"]').map(function(){return this.value;}).get();}
var post={'categorias':categorias,'postParent':postParent,'idPost':idPost};$.ajax({beforeSend:function(qXHR,settings){$('.verMasPost').addClass('active');$('.verMasPost span').addClass('loader');$('.loaderContent').fadeIn(300);},complete:function(){$('.verMasPost').removeClass('active');$('.verMasPost span').removeClass('loader');$('.loaderContent').fadeOut(300);},type:"post",url:template_url+'/wp-admin/admin-ajax.php',data:{'action':"verMasPost",'datos':post},success:function(response){if(response!=''){$('#idPost').remove();$('.listCourse ').append(response);}else{$('.loaderContent').fadeOut(300);$('.verMasPost').fadeOut(300);}}});});}},titlestyle:{init:function(){$('.title_style, .title, .title_white').each(function(){$(this).append('<div class="sub-rayado"></div>');});$(window).bind('resize',function(){var ancho=$(window).width();var ancho_content=$('.spacing_house').width();var spacing=(ancho-ancho_content)/2;setTimeout(function(){$('.title_style, .title, .title_white').each(function(){var ancho_title=$(this).find('.titledisplay').width();$(this).find('.sub-rayado').css({'width':parseInt(ancho_title)+parseInt(spacing)+10,'left':parseFloat('-'+spacing)});});},250);});$(window).trigger('resize');}},galeria:{init:function(){var dispositivo=navigator.userAgent.toLowerCase();if(dispositivo.search(/iphone|ipod|android/)>-1){var html=[];$('.gallerycontainer .clearfix').each(function(){html.push($(this).html());});setTimeout($('.galleryscroll').html(html).bxSlider({adaptiveHeight:true,autoControls:true,slideWidth:380,}),200);}else{$(window).bind('resize',function(){var total=0;$('.gallerycontainer .clearfix').each(function(){var nuevo_ancho=0;var resta=0;$(this).find('a').each(function(){if(!$(this).hasClass('img3')&&!$(this).hasClass('img4')&&!$(this).hasClass('img6')){nuevo_ancho=$(this).width()+nuevo_ancho+1;$(this).parent().css('width',nuevo_ancho);};});total=nuevo_ancho+total;$(this).parent().css('width',total);});$('.galleryscroll').jScrollPane();});$(window).trigger('resize');$('.galleryscroll').jScrollPane();}}},bxslider_seminarios:{init:function()
{var dispositivo=navigator.userAgent.toLowerCase();if(dispositivo.search(/ipad/)>-1){if($('.spacing_sem #content_img').length>1){$('.spacing_sem .bx-controls').css('display','block');$('.spacing_sem .slideimg').bxSlider({minSlides:1,maxSlides:1,moveSlides:1,hideControlOnEnd:true});};}else if(dispositivo.search(/iphone|ipod|ipad|android/)>-1){if($('.spacing_sem #content_img').length>1){$('.spacing_sem .bx-controls').css('display','block');$('.spacing_sem .slideimg').bxSlider({minSlides:1,maxSlides:1,moveSlides:1,hideControlOnEnd:true});};}else{if($('.spacing_sem #content_img').length>1){$('.spacing_sem .slideimg').bxSlider({slideWidth:381,minSlides:1,maxSlides:3,nextSelector:'.sem-and-wksh .triangulo_izq',prevSelector:'.sem-and-wksh .triangulo_der',infiniteLoop:false,autoControls:true,slideMargin:30});};}},cursos:function()
{var dispositivo=navigator.userAgent.toLowerCase();if(dispositivo.search(/iphone|ipod|ipad|android/)>-1){if($('.house-course .slide .sub_title').length>1){$('.house-course .slide').bxSlider({slideWidth:405,minSlides:1,maxSlides:3,nextSelector:'.house-course .triangulo_izq',prevSelector:'.house-course .triangulo_der',slideMargin:68});};}else{if($('.house-course .slide .sub_title').length>1){$('.house-course .slide').bxSlider({adaptiveHeight:true,autoControls:true});};}}},scrollpane:{init:function()
{$('.scroll-pane').jScrollPane();}},selectmenu:{init:function()
{var select=$('.contacto-one .none,.contacto_blue .none').html();$('select.files').html(select);$(".files").selectmenu();$('.detalle .files').fadeOut();$('.detalle span.files').fadeOut();}},menu:{init:function()
{$(".nav li.first").hover(function(){var self=$(this);$(this).find("ul").stop(true,true).fadeIn(500);if(!$(this).hasClass('hover')){var alto=$(this).find("ul").height();var paddingtop=$(this).find("ul li").first().css('padding-top');var paddingbottom=$(this).find("ul li").first().css('padding-bottom');alto=parseInt(alto)-parseInt(paddingbottom)-parseInt(paddingtop);$(this).find("ul > li").css('height',alto);$(this).find("ul li li").css('height','auto');$(this).addClass('hover');};},function(){$(this).find("ul").fadeOut(300);});}},date:{init:function()
{$('.datepicker').datepicker();}},conteo:{init:(function(){})},slide:{init:function(){$(window).bind('load',function(){var ancho=$(window).width();if(ancho<=400){$(".content_exhi").hover(function(){$(this).find(".descri").stop(true,false).animate({height:150},500);},function(){$(this).find(".descri-2").stop(true,false).animate({height:100},500);});}
else{$(".content_exhi").hover(function(){$(this).find(".descri").stop(true,false).animate({height:311},500);},function(){$(this).find(".descri-2").stop(true,false).animate({height:100},500);});}});}},speed:{init:function(){$('.toggleSpeed').bind('click',function(e){e.stopPropagation();});$('.toggleSpeed img').bind('click',function(e){e.preventDefault();e.stopPropagation();if($(this).parent().find('form').css('display')==='block'){$(this).parent().find('form').fadeOut(400);}else{$(this).parent().find('form').fadeIn(400);};});$('html').bind('click',function(e){$('.buscador form').fadeOut(400);});}},fade_button:{init:function(){$(window).scroll(function(){if($(this).scrollTop()>0){$('.up_index').fadeIn();}else{$('.up_index').fadeOut();}});}},up:{init:function(){$('.up_index').click(function(){$('body,html').animate({scrollTop:0},500);return false;});}}}