/*
Powered by ueeshop.com		http://www.ueeshop.com
å¹¿å·èéç½ç»ç§ææéå¬å¸		020-83226791
*/

var lang_obj={
	global:{
		'ok':'OK',
		'add':'Add',
		'edit':'Edit',
		'submit':'Submit',
		'confirm':'Confirm',
		'cancel':'Cancel',
		'close':'Close',
		'return':'Back',
		'copy_confirm':'Enter the product replication mode, continue?',
		'copy_model_confirm':'Enter the attribute replication mode, continue?',
		'del_confirm':'Irretrievable after deletion, continue?',
		'reset_confirm':'Confirm to restore the default settings, continue?',
		'used_confirm':'Ready to turn on the batch mode, continue?',
		'close_confirm':'Ready to turn off the batch mode, continue?',
		'my_order_confirm':'Ready to turn on the sorting mode, continue?',
		'sold_in_confirm':'Ready to turn on the sales mode, continue?',
		'sold_out_confirm':'Ready to turn on the off sales model, continue?',
		'merge_confirm':'After the order is closed, the previously split waybill will be deleted, continue?',
		'facebook_release_confirm':'Ready to mass release the product to the Facebook store, ready to go?',
		'facebook_delete_confirm':'Ready to remove products from the Facebook store in bulk, ready to go?',
		'can_reg_confirm':'Click OK to cancel the registration and continue?',
		'can_set_confirm':'Click OK to cancel the settings and continue?',
		'recall_confirm':'Ready for bulk recall, continue?',
		'selected':'Please select',
		'data_posting':'Data being submitted...',
		'loading':'Loading...',
		'sync':'Data being synchronization...',
		'delete':'Progressing...',
		'confirm_password_error':'Login password does not match with the confirmed password, please re-enter!',
		'del_dat_select':'Please select the item to be deleted',
		'used_dat_select':'Please select the item to be started',
		'close_dat_select':'Please select the item to be closed',
		'dat_select':'Please select the chosen item',
		'correct_message':'Please fill in the correct data',
		'n_y':['No', 'Yes'],
		'display':['Show', 'Hide'],
		'open':'Unfold',
		'pack_up':'Fold',
		'del':'Delete',
		'picture':'Picture',
		'picture_name':'Picture Name',
		'set_error':'Setup failed unknown mistakes!',
		'coupon':'Coupon',
		'view_it':'View it',
		'save_success':'Save Success!',
		'save_fail':'Save Fail!',
		'option':'Option',
		'source':{'pc':'PC', 'mobile':'Mobile'},
		'select_all':'Select All',
		'copy_complete':'It has been copied and can be pasted.',
        'shop_now':'Shop Now',
        'unrepeat':'Do not repeat the operation!',
	},
	format:{
		'mobilephone':'Please fill in the phone number correctly!',
		'telephone':'Please fill in the telephone number!',
		'fax':'Please fill in the fax number correctly!',
		'email':'Please fill in the email address correctly!',
		'length':'Incorrect length! You need to fill in %num% digits.'
	},
	signIn:{
		'title':'Sign In',
		'error_note':'Incorrect email address or password. Please try again.<br> Make sure the Caps Lock is off before you enter password.',
		'email':'Email',
		'password':'Password',
		'forgot':'Forgot your <a href="/account/forgot.html" class="forgot">password</a>?',
		'stay_note':'Stay signed in <span>Protect your privacy - sign out when you\'re done.</span>',
		'sign_in':'Sign in',
		'join_fee':'Join Free'
	},
	newsletter:{
		'success':'Added to subscribe successful!',
		'exists':'This mailbox already exists subscription!',
		'your_questions':'Please write down your questions...',
		'your_email':'Your email'
	},
	language:{
		'cn':'Chinese',
		'en':'English ',
		'jp':'Japanese',
		'de':'German',
		'fr':'French',
		'es':'Spanish',
		'ru':'Russian',
		'pt':'Portuguese',
		'zh_tw':'Traditional Chinese',
		'it':'Italiano',
		'ko':'Korean',
		'my':'Burmese',
		'vi':'Vietnamese',
		'th':'Thai',
	},
    time:{
		'months':['January', 'February', 'March', ' April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
		'weekdays':['Sun', 'Mon', 'Tues', 'Wed', 'Thur', 'Fri', 'Sat']
    },
	manage:{
		global:{
			'name':'Name',
			'more':'More',
			'save':'Save',
			'edit':'Edit',
			'default':'Default',
			'del_success':'Successfully deleted!',
			'del_fail':'Failed to delete!',
			'can_log':'Allow login!',
			'cant_log':'Login is forbidden!',
			'admin':'Admin',
			'export_success':'Export success!',
			"photo_gt_2m":"Selected pictures below are larger than 2MB: ",
            'you':'You',
			'use_plugin':'Use plugin',
			"load_more":"Load more",
			"no_more":"No more",
			"update_status":['Processing', 'Completed', 'Operation Failed'],
			"u_file_size_2big":"Your server space storage capacity is full, please contact businessï¼QQï¼2046307556",
            'disk_space_not_enough':'The site capacity is insufficient, please contact customer service.'
		},
		error:{
			'no_data':'No data',
			'no_table_data':'There is currently no data',
			'add_now':'Add Now',
			'no_prod_data':'No product data',
			'supplement_lang':'Please fill in the language version!',
		},
		tips:{
			'plugins_close':'Uninstalling the app causes the corresponding function to be unavailable, are you sure?',
		},
		frame:{
			'time':'Time',
			'status':'Status',
			'support':['Enterprise QQ', 'Working Hours', 'Telephone', 'We Chat', 'Complaint call', 'Website Expiration Time'],
			'data_backup':'Data Backup',
			'backup':['Database', 'Folder'],
			'file_upload':'SELECT FILES'
		},
		translation:{
			'translation':'Translation',
			'in_translation':'in translation...',
			'char':'char',
			'translation_success':'success',
			'translation_fail':'fail'
		},
		account:{
			"log_in":"The system is trying to log in, please wait...",
			"log_in_ok":"Successful login, the page jumps, please wait...",
			"order_quantity":"Website Order",
			"page_view":"Site Visits",
			"success_cache":"Cache has been cleared successfully!",
			"percentage":"Percentage",
			"picture_tips":"You have uploaded more than xxx pictures and cannot uploaded anymore!",
			"password_tips":"Re-password do not match, please re-enter!"
		},
		set:{
			"select_once_language":"Please select at least one language version",
			"print_0":"Print the customs declaration",
			"print_1":"Print invoice",
			"platform_ary":{'SignIn':'Login','Pixel':'Statistics','PageId':'Messenger'},
			'open_api_refresh':'Update AppKey, continue?',
			'dhl_info':'SiteID (Identifies the sender of the request message. It is a mandatory field in the request message.)<br />Password (Authenticates the sender of the message. It is a mandatory field in request message.)<br />CountryCode (Origin Country/Region Code)<br />Postalcode (Origin Postal code)<br />"Account" and "ExchangeRate" do not need to fill in content'
		},
		module:{
			"sure_module":"Are you sure to choose this style?",
			"name":"Name",
			"url":"Links address",
			"target":"New window",
			"cdx_10":'<br />VIP theme free for 30 days',
		},
		counrtry:{
			"state":"Province",
		},
		photo:{
			"empty_temp":"Temporary folder has been cleared successfully!",
			"move_success":"Removed successfully",
			"picture_upload":"Picture Upload",
			"upload_success":"The image was uploaded successfully!",
			"too_many":"There are too many pictures, please operate in batches!",
			"size_limit":"Each pictures size should be smaller than 2MB!",
			'no_picture':"Please upload an image"
		},
		shipping:{
			"area_config":"Area Setting",
			"shipping_config":"Shipping Setting",
			"documentation":"Documentation",
			"overseas_del_confirm":"After the deletion, the relevant shipping model, product attribute related items, are deleted together, and can not be restored. continue or not?",
			"fill_start_weight":"Please fill in the interval start weight first.",
			"fill_num":"Please fill in the correct value first.",
			"add_area_suc":"Add region success.",
			"select_area":"Please select a region first.",
			"shipped":"Shipped",
			"agree":"Please read carefully and agree to the above",
		},
		orders:{
			'refund':'Refund',
			'refund_status':['Failed', 'Completed', 'Pending'],
			'transaction':'Transaction ID',
			'refund_amount':'Refund Amount',
			'refund_time':'Refund time',
			'refund_confirm':'Please confirm whether to continue the refund operation?',
			'change_status':'Can\'t recover after changing the status, continue?',
			'change_confirm':'Please confirm whether to continue the changing status?',
			'not_orders':'Not order',
		},
		products:{
			"category_tips":"Please select the product category",
			"stock":"Stock",
			"qty":"Quantity",
			"price":"Price",
			"mark_up":"Price increased",
			"discount":"Discount",
			"color":"Color",
			"associated_picture":"Associated Picture",
			"master_pictures":"Master Pictures",
			"pictures":"Pictures",
			"group_attr":"Combination Properties",
			"attribute":"Attribute",
			"tab":"Tab",
			"pro_screen":"Screen",
			"screen_item":"Screen",
			"attr_edit":"Attribute Modify",
			"tab_edit":"Tab Modify",
			"attribute_center":"Attribute Center",
			"tab_myorder":"Tab Sort",
			"wholesale_discount_notes":"The price of the product attribute selected by the current station is the unit price, the calculation of the wholesale price will be calculated in a discounted way",
			"prefix_tips":"The prefix of product number canât be empty!",
			"sync_change_account":"Switching account...",
			"copy_complete":"Has been copied to the local product management system!<br />Can be viewed in the <a href='./?m=products&a=products&Status=2' target='_blank' class='red'>Offline Products</a>",
			"price_count":"The wholesale price can not be set more than 5!",
			"batch_notes":"Same %txt% sync",
			"pro_count":"%num% products",
			"used_pro_count":"%num% products in used",
			"placeholder":"After filling in the content, press the Enter key to save.",
			"modification_title":"%title% modification",
			"pictures_title":"%title% pictures",
			"price_null":"When setting the price, the price cannot be 0",
			"attr_null":"Already have the same name attribute, please re-fill",
			"desc_en":"English description",
			"desc_cn":"Chinese description",
			"hscode":"Hscode",
			"units":"Unit",
			"customs_value":"Customs declaration unit price",
			"prodtype_name":"Product type",
			"prodtype":{"1":"General", "2":"Sensitive", "3":"Charged"},
			"apply":{"website":"Shared across websites", "categories":"Shared multiple categories", "category":"Current category", "product":"Current product"},
			upload:{
				'uploading':'Image uploading..',
				'uploaded':'Image import completed',
				'upload_failed':'Image import failed',
				'upload_picture_failed':'%number% pictures are limited to upload because the picture size is greater than 1200 pixels or the picture capacity is greater than 2MB',
				'imported':'Import completed',
				'imported_all':'All import completed'
			},
			sync:{
				'start_sync_products':'Start syncing product!',
				'not_repeat_task':'Do not repeat the sync task!',
				'sync_confirm':'Ready to start syncing products, continue?',
			},
            notes:{
            	'edit_attribute':'Modify the following attributes, which will be batch updated to products of the same attribute.',
				'edit_attribute_option':'Modify the following attribute options to batch update products to the same attribute option.',
				'edit_tab':'Modify the following tab, which will be batch updated to products of the same tab.',
                'edit_tab_myorder':'Modify tab ordering, sorting tabs that modify other related products at the same time.',
                'all_products_used':'All products available',
            }
		},
		sales:{
			"seckill":"Seckilling",
			"promotion":"Promotion",
			"proName":"Product Name",
			"proPrice":"Product Price",
			"proNumber":"Product Number",
			"proBiref":"Brief introduction",
			"start_time":"Starting time",
			"duration":"Duration",
			"hour":"Hours",
			"tuan_price":"Group-buying price",
			"buyer_count":"Purchases",
			"total_count":"Restrictions",
			"promotion_price":"Total promotion price",
			"seckill_price":"Price spike",
			"qty":"Quantity",
			"remainder_qty":"Residual quantity",
			"max_qty":"Purchase Ceiling",
			"reverseAssociate":"Inversely correlated (This combination will be displayed simultaneously for the associated products when no combination is set)",
			"mainArea":"The product already exists in the main products area",
			"relatedArea":"The product already exists in the bundled products area",
			"salesNotice":'Drag the product list on the right side to <b class="fc_red">"Salesing products area"</b>',
			"holidayNotice":'Drag the product list on the right side to <b class="fc_red">"holiday-template products area"</b>',
			"seckillNotice":'Drag the product list on the right side to <b class="fc_red">"seckilling products area"</b>',
			"tuanNotice":'Drag the product list on the right side to <b class="fc_red">"group-buying products area"</b>',
			"relatedNotice":'Drag the product list on the right side to <b class="fc_red">"main products area"</b> and <b class="fc_red">"bundled products area"</b>',
			"beyondNumber":"Exceed the maximum limit number: ",
			"condition":"Consumption Conditions",
			"discount":"Discount",
			"money":"Money",
			"condition_tips":"This coupon can only be used when the shopping amount reaches the set value; there will be no restrictions on the usage conditions if you set 0",
			"discount_tips":"Please enter the percentage of discount; 20% is equivalent to 80% off, 80% is equivalent to 20% off",
			"money_tips":"Please enter the coupon code between 8 to 15 digits",
			"coupon":{
				"user":"Member",
				"level":"Level",
				"products":"Product",
				"products_category":"Category",
				"tags":"Tag",
			},
			"del_seckill":"Are you sure you want to delete all spike products in this time period?",
			"lastpage":"It is already the last page!",
			"del_coupon":"If you delete the coupon, the coupon you have already received will be deleted and cannot be recovered. Are you sure you want to delete it?",
		},
		email:{
			"load_error":"Template data reading failed, please try again later!",
			"not_model":"No template is chosen!",
			"not_user":"No Member!",
			"not_content":"No Content!",
			"send_success":"Sent successfully!",
			"send_failed":"Sent failed!",
			"not_tit_or_desc":"The message title or content is empty!",
			"no_subscribed":"No Subscribed"
		},
		mta:{
			"traffic_time":['Last 30 days', 'Today', 'Yesterday', 'Last 7 days', 'Last 15 days'],
			"statistics_name":['Visitors', 'Pageviews'],
			'order_count':'Order Quantity',
			'buy_count':'Sales Volume',
			'also_buy':'Buy other at the same time',
			'country':'National ranking',
			'equipment_ratio':'Equipment Ratio',
			'order_amount':'Order Amount',
			'total_sales':'Total Sales',
            'conversion_charts':['Direct Access', 'Social Platforms', 'Search Engine', 'Other'],
            'total_ratio':'Total ratio',
		},
		app:{
			'app':'App',
			'facebook_store':{
				'title':'Facebook Page Store',
				'appid':'AppId',
				'page':'Page Tab URL',
				'add_page':'Add Page Tab',
				'authorized':'Click Authorization'
			},
			'facebook_ads_extension':{
				'store':'Facebook Store',
				'store_id':'Your Facebook Store ID',
				'manage_settings':'Manage Settings',
				'get_started':'Get Started',
				'create_ad':'Create Ad',
				'tips':'Tip: Please connect to the VPN before performing the following operations.'
			},
			'massive_email':{
				'authorized_email':'Authorized account:',
				'authorized_key':'Authorized Key:',
			},
			'dhl_account_open':{
				'filename_error':'A file has been uploaded. If you want to replace the file, you need to delete the corresponding file path and upload it.',
			},
			'dhl_account_info':{
				'pickupAccountId':'DHL Pickup Account',
				'soldToAccountId':'DHL Soldto Account',
				'prefix':'Customer prefix',
				'un_close_out':'The waybill has not been submitted, no logistics information',
				'unit_price':'Unit price',
				'quantity':'Quantity',
				'origin':'Place of origin',
				'remark_en':'Remarks',
			},
			'asiafly':{
				'merchantCode':'merchantCode',
				'privateKey':'privateKey',
				'use':'ä½¿ç¨',
				'type_ary':['', 'æ®è´§', 'ææ', 'å¸¦çµ'],
				'shipping':'ç©æµ',
			},
            'paypal_dispute':{
                'loading':'Updating dispute information...',
                'updated':'Update completed',
            },
			'facebook_sinoclici':{
				'sino_phone':'Phone Number',
				'sino_email':'Email Address',
				'sino_licence':'Business license photo',
				'sino_industry':'Industry Code',
				'sino_industry_array':{'1':'E-Commerce'},
			},
			'custom_attributes':{
				'add_extension':'Add extension',
			}
		},
		view:{
			'layout':'Layout',
			'effect':'Effect',
			'loading':'Try to load the template',
			'down_load':'Pull down to load more',
			'no_data':'Already in the end',
			'guide':'Mouse over to edit content',
			'guide_1':'Click the button to enter [background mode] to edit content and website settings.',
			'no_edit_tips':'Please enter the background management mode for editing',
			'next_btn':'Next step',
			'rename':{
				'name':'Name',
				'job':'Job',
				'brief':'Introduction',
				'button':'Button',
				'vatar':'Vatar'
			},
			'use_plugins':'Use plugin',
			'easy_set':'Easily complete beautiful content layout',
			'set':'Set up',
			'products_page_type':'Product page display type',
			'products_page_type_ary':{
				'1':'Marketing',
				'2':'Brand',
				'3':'Customize'
			}
		},
		cdx:{
			'agreement_tips':'Please read the user agreement and agree to confirm the payment.',	
		}
	},
	products:{
		'warning_number':'Purchase fewer than or more than the stock MOQ',
		'warning_MOQ':'Low from the MOQ',
		'warning_Max':'The maximum number of purchases %num%',
		'warning_stock':'Higher than the inventory %num%',
		'warning_attribute':'Please select parameters',
		'select_country':'--Please select your country--',
		'sign_in':'Please sign in first!',
		'free_shipping':'Free Shipping',
        'free':'Free',
		'via':'via',
		'no_optional':'No optional',
		'ships_from':'Ships from',
		'shipEstimated':'Estimated Delivery Time',
	},
	review:{
		'rating':'Your rating is required.',
		'review_title':'Your name is required.',
		'review_max':'Remaining characters:Please don\'t exceed 5,000 characters.',
		'reply_here':'Add your reply here...',
		'reply_tips_null':'Please input your reply.',
		'reply_tips_max':'Is your Review Content correct? Our system requires a maximum of 5000 characters.',
		'reply_tips_successed':'Submitted successfully.',
		'reply_tips_success':'Return the contents of submitted successfully, waiting for the audit.',
		'reply_tips_error':'Please refresh this page and try again.',
	},
	cart:{
		'itemCount':'%num% item',
		'itemsCount':'%num% items',
		'processing':'Processing, please wait...',
		'processing_str':'Processing',
		'checkout_str':'Proceed to Checkout',
		'order_str':'Place Your Order',
		'checked_error':'Please select at least one item',
		'attribute_error':'There was an error in the product information, please remove this product and then re purchase.',
		'address_error':'Please enter your shipping address or choose one from your previously entered address. Ensure information, please click save after completed.',
		'shipping_error':'Please choose a delivery method.',
		'payment_error':'Please choose a payment method.',
		'product_error':'Your shopping cart is empty.',
		'low_error':'Your total product has not yet reached the lowest consumption value of the website',
		'stock_error':'Some products have insufficient inventory, you can not create an order correctly, adjust the purchase quantity.',
		'prod_stock_error':'This item is low in stock',
		'no_delivery':'Sorry! No delivery to this Country/Region!',
		'additem_0':'This product was successfully added to cart!',
		'additem_1':'<b class="FontColor">%num%</b> Item(s) in your cart. Subtotal: ',
		'consumption':'Requires a minimum purchase of <span class="FontColor low_info">%low_price%</span>. And you still need <span class="FontColor low_info">%difference%</span> to meet the requirements.',
		'return_shopping':'Return to Shopping',
		'proceed_checkout':'Proceed to Checkout',
		'arrival_info_0':'Has been successfully submitted to the business, the products cover will immediately notify the customer.',
		'arrival_info_1':'Please log in to apply for arrival notice.',
		'arrival_info_2':'This product has applied for the arrival notice!',
		'use_shipping_address':'Use This Shipping Address',
		'coupon_title':'Enter your coupon code',
		'coupon_tips':'The coupon code "<strong>%coupon%</strong>" is valid!<br /> Your discount is',
		'coupon_code':'Coupon Code',
		'apply':'Apply',
		'select_y_country':'Select you country',
		'remove':'Remove',
        'batch_buy_select':'Please select the product you want to buy!',
        'batch_buy_option':'Please select product Options!',
		'batch_remove_select':'Please select the item(s) you want to delete!',
		'batch_remove_success':'Product(s) deleted successfully!',
		'batch_remove_error':'Product(s) deletion failed!',
		'continue_str':'Continue Checkout',
		'total_amout':'Total Amount',
		'insurance':'Add Shipping Insurance to your order',
		'coupon_tips_to':'The coupon code %coupon% is invalid. It either does not exist, has not been activated yet, or has expired.',
		'coupon_tips_th':'The coupon code <strong></strong> is invalid. It either does not exist, has not been activated yet, or has expired.',
		'coupon_price_tips':"The total amount of the product is lower than the coupon's consumption conditions, the system automatically cancel the coupons now used.",
		'shipping_method_tips':'Please select a shipping method!',
		'cart_tips':'1 item added to cart',
		'plz_sel_para':'Please select parameters',
		'del_confirm':'Are you sure to delete it?',
		"paypal_tips":"Please select the same country as the PayPal account address information.",
		'payment':'Payment Method',
		'checkout':'Checkout',
		'pay_now':'Pay Now',
		'moreAddress':'More Address',
		'foldAddress':'Fold Address',
		'tips':{
			'no_delivery':'We don\'t offer shipping to %country%.',
			'contact_us':'Contact Us: <a href="mailto:%email%">%email%</a>',
		},
		'coupon_tips':{
			'0': 'The coupon code <strong>%code%</strong> is invalid. It does not exist.',
			'-1': 'The coupon code <strong>%code%</strong> is invalid. It has not been activated yet.',
			'-2': 'The coupon code <strong>%code%</strong> is invalid. It has expired.',
			'-3': 'The coupon code <strong>%code%</strong> is invalid. It has already used.',
			'-4': 'The coupon code <strong>%code%</strong> is invalid. You could use the coupon when the order amount reach to <strong>%price%</strong>.',
			'-5': 'The coupon code <strong>%code%</strong> is invalid. It\'s not received by the customer.',
			'-6': 'The coupon code <strong>%code%</strong> is invalid. Some products are not included in the offer of this coupon.',
		},
		'card_tips':{
			'card_type' : 'Please select the card type',
			'card_num'  : 'Card Number can not be null, it must be numeric, the length must be 16 or 15.',
			'card_month': 'Card Expire Month can not be null.',
			'card_year' : 'Card Expire Year can not be null.',
			'card_cvv'  : 'CVV2/CSC is incorrect, it must be numeric, the lenght must be 3!',
			'card_bank' : 'Issuing Bank can not be null!'
		}
	},
	orders:{
		'choose_payment':'Choose payment method',
		'order_total':'Grand Total'
	},
	seckill:{
		'loading_tips':'There is no more products',
		'no_products':'Not match any products',
		'end':'Finished'
	},
	user:{
		'send_email_ture':'An email has been sent to you successfully. Please enter your email address and check the verification email.',
		'send_email_false':'Sorry, the email was sent in failure because of system problem. Please try again later.',
		'favorite_success':'This product Bookmarked!',
		'favorite_saved':'This product has been favorited!',
		'favorite_remove':'Has been removed!',
		'go_to_view':'Go to view',
		'order_cancel':'Are you sure you want to delete this pending order?',
		'sure':'Are you sure?',
		'delete_shipping':'Are you sure you want to delete this address?',
		'content':'Content',
		'upload':'Upload',
		'image':'Image',
		'send':'Send',
		'reg_error':{
			'PleaseEnter':'Please enter your %field%.',
			'Email':'Please enter an email address.',
			'EmailFormat':"The email you've entered is invalid. Please check your email and try again.",
			'PWDConfirm':'Please re-enter your new password.',
			'PWDNotMatch':'Your passwords do not match, please try again.'
		},
		'address_tips':{
			'PleaseEnter':'Please enter your %field%.',
			'email':'Please enter your Email.',
			'email_format':'Email entered doesn\'t match with confirm Email value.',
			'firstname':'Please enter your first name.',
			'firstname_length':'Your First name must contain a minimum of 2 characters.',
			'lastname':'Please enter your last name.',
			'lastname_length':'Your First name must contain a minimum of 2 characters.',
			'address':'Please enter shipping address.',
			'address_length':'Your shipping address should be at least 5 characters long.',	
			'city':'Please enter your city.',
			'city_length':'Your city should be at least 3 characters long.',
			'country':'Please select your destination country/region.',
			'state':'Please select your state/province/region.',
			'taxcode':'Sorry, your %str% is required.',
			'taxcode_length':'Your %str% must contain a minimum of %taxlen% numbers.',
			'tariff':'Sorry, your %str% number is required.',
			'tariff_length':'Your %str% number must contain a minimum of 11 numbers.',
			'zip':'Please enter a ZIP / postal code.',
			'zip_length':'Your ZIP / postal code should be at least 4 digits long.',
			'phone':'Please enter your phone number.',
			'phone_format':'Please enter a valid phone number.',
			'phone_length':'Your phone number must be at least 7 digits.',
		}
	},
	payment:{
		'required_fields_tips':'Required fields are blank',
		'already_paid_tips':'Already paid',
		'abnormal_tips':'Abnormal payment method, it is recommended to change other payment methods',
		'cancel_tips':'Confirm, you will abandon this payment and cannot return to continue payment.',
	},
	excheckout:{
		'coupon_code':'Coupon Code',
		'apply':'Apply',
		'coupon_txt':'The coupon code "<strong></strong>" is valid!',
		'discount_txt':'Your discount is',
		'exp_date':'expiration date',
		'remove':'Remove',
		'coupon_error':'The coupon code <strong></strong> is invalid. It either does not exist, has not been activated yet, or has expired.',
	},
	verification:{
		'ver_click':'Click to verification',
		'ver_slide':'Slide to verification',
        'ver_error':'Verification code error!',
		'drag_picture':'Drag the picture to complete the verification',
		'ver_successed':'Successful verification',
		'ver_failed':'Verification failed',
		'please_verification':'Please complete the image verification'
	},
	mobile:{
		'no_data':'No data Yet',
		'load_more':'Load More',
	}
};