
// Generated by CoffeeScript 1.6.3
(function() {
  var APPIER_TRACKING_CODE, FORM_ID, HOST, TYPE1_CHECK_PHONE_API, TYPE1_SUBMIT_FORM_API;

  APPIER_TRACKING_CODE = 'l5j47832M42gL6O';

  FORM_ID = 5716517316460544;

  HOST = 'http://xpost.c.appier.net';

  TYPE1_CHECK_PHONE_API = HOST + '/chkdup/type1/telno';

  TYPE1_SUBMIT_FORM_API = HOST + '/doform/type1';

  window.get_query_parameter = function(name) {
    var query, token, _i, _len, _ref;
    _ref = window.location.search.substr(1).split('&');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      token = _ref[_i];
      query = token.split('=');
      if (query[0] === name) {
        return query[1];
      }
    }
  };

  window.submitClicked = function() {
    var phone_number;
 	phone_number = $('#InputPhone').val().replace(/[^\d]/g, '');
    if (phone_number.indexOf('09') !== 0 || phone_number.length !== 10) {
      alert('請確認您的手機號碼');
      return false;
    }
    if ($('#InputName').val() == "") {
      alert('請填寫有效姓名');
      return false;
    }
    if($('#age_group').val() == 0){
      alert('請填寫年齡');
      return false;
    }
    $.get(TYPE1_CHECK_PHONE_API, {
      formid: FORM_ID,
      telno: phone_number
    }).done(function(dup) {
      var traffic_source;
      if (dup === "1") {
        return alert('此手機號碼已申請過，無法重複申請');
      } else {
        return submitRegistration(FORM_ID, $('#InputName').val(), phone_number, $('#age_group').val());
      }
    }).fail(function() {
      return alert('網路連線問題，請再試一次');
    });
    return false;
  };

  window.submitRegistration = function(formid, name, telno, age) {
    var jqxhr;
    ga('send','event','form','submit');
    Appier.appierTrack(APPIER_TRACKING_CODE, {uu:telno});
    return jqxhr = $.post(TYPE1_SUBMIT_FORM_API, {
      formid: formid,
      name: name,
      telno: telno,
      ext1: age,
    }).done(function() {
      if (jqxhr.status === 200) {
        return window.location = 'free_result.html';
      } else {
        return alert('網路連線問題，請再試一次');
      }
    });
  };

}).call(this);