var spamAbuseScript={initSpamAbuse:function(){$('.other-option .control-label').each(function(){var label=$(this);label.parents('.control-selection').unbind();label.parents('.control-selection').click(function(){$(this).addClass('edit-other');if(!$(this).find('.radio-check').is(':checked')){$(this).find('.control-label').show();$(this).find('.other-input').val('');$(this).find('.other-input').addClass('hidden');$(this).parents('.answer-options').find('[id^=errorSpan].error').html('');$(this).parents('.answer-options').find('[id^=errorSpan].error').addClass('hidden');}else{$(this).find('.control-label').hide();$(this).find('.other-input').removeClass('hidden').focus();}});});}};var validateReportAbuse=(function(){var spamValidationErrorArray;var spamSectionDiv;var sectionID;var type;var isRequired;var validationType;var sections;function execute(allSections){sections=allSections;resetAndHideSpamErrors();spamValidationErrorArray=[];validateRequiredSections();var requiredValidationErrors=getRequiredValidationErrors();if(requiredValidationErrors.length&&requiredValidationErrors.length>0){displaySpamValidation(requiredValidationErrors);return 1;}
return 0;}
function validateRequiredSections(){for(var i=0;i<sections.length;i++){setSectionDiv(sections[i]);validateSection(sections[i]);addValidationForChange();}}
function setSectionDiv(currentSection){spamSectionDiv=$('#SpamQuestionSection_'+currentSection.sectionID);}
function validateSection(section){sectionID=section.sectionID;type=section.questionType;isRequired=section.required;validationType=section.validationType;if(type==='M'&&isRequired&&validationType==1){return multi_choice.validate();}else if(type==='T'&&validationType==2){return text.validate();}}
function addValidationForChange(){if(type==='M'&&isRequired&&validationType==1){return multi_choice.addValidationEvent();}else if(type==='T'&&validationType==2){return text.addValidationEvent();}}
function validateCurrentSection(currentSection){for(var i=0;i<sections.length;i++){if(sections[i].sectionID==currentSection){executeOnUpdate(sections[i]);break;}}}
function executeOnUpdate(section){resetAndHideErrors();setSectionDiv(section);validateSection();var requiredValidationErrors=getRequiredValidationErrors();if(requiredValidationErrors.length&&requiredValidationErrors.length>0){displaySpamValidation(requiredValidationErrors);}}
function validateEmail(textValue){var regx=new RegExp("^([a-zA-Z0-9\\_\\-\\.]+)*(\\+[a-z0-9-]+)?@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$");return regx.test(textValue&&textValue.trim());}
function isEmpty(value){return typeof value!='undefined'&&value.trim().length==0}
function removeErrorsFromArray(sectionID){spamValidationErrorArray=$.grep(spamValidationErrorArray,function(error){return error.sectionID!=sectionID;});}
function getRequiredValidationErrors(){var forcedValidationErrors=[];var counter=0;for(var i=0;i<spamValidationErrorArray.length;i++){forcedValidationErrors[counter++]=spamValidationErrorArray[i];}
return forcedValidationErrors;}
function addErrorToValidationArray(errorJSON){removeClassHiddenFromErrorSpan(spamSectionDiv);var spamFound=spamValidationErrorArray.some(function(existingError){return existingError===errorJSON;});if(!spamFound){spamValidationErrorArray.push(errorJSON);}}
function removeClassHiddenFromErrorSpan(spamSectionDiv){$(spamSectionDiv).find('span[id^=errorSpan_]').removeClass('vhidden');}
function displaySpamValidation(forcedValidationErrors){populateSpamQuestionErrors(forcedValidationErrors);}
function populateSpamQuestionErrors(questionSpamValidationErrors){for(var i=0;i<questionSpamValidationErrors.length;i++){var validationError=questionSpamValidationErrors[i];highlightErredInputTextAndTextArea(validationError.sectionID);addErrorMessageToErrorSpans(validationError);}}
function addErrorMessageToErrorSpans(validationError){var message=getQuestionErrorMessage(validationError);$('#errorSpan_'+validationError.sectionID).html(message?message:validationError.messageKey);if(typeof message!='undefined'&&message!=''){$('#errorSpan_'+validationError.sectionID).removeClass('hidden vhidden');}}
function highlightErredInputTextAndTextArea(sectionID){var $this=$('#errorSpan_'+sectionID);if($this.length==1){if(errorForOtherInChoiceQuestion()){$this.parent().find('.other-input').addClass('error-line');}}
function errorForOtherInChoiceQuestion(){return $this.parent().is(".answer-options")&&$this.parent().is(".other-option")&&$this.parent().find('.other-input:not(".hidden")').length>0&&$this.parent().find('.other-input:not(".hidden")').prop('value')!=undefined&&$this.parent().find('.other-input:not(".hidden")').prop('value').trim().length===0;}}
function getQuestionErrorMessage(validationError){return getTranslatedValidationMessage(validationError.messageKey,validationError.replacements);}
function resetAndHideSpamErrors(){$('[id^=errorSpan_]').html('');$('[id^=errorSpan_], .error-wrapper').addClass('vhidden');$('.error-line').removeClass('error-line');}
var multi_choice={validate:function(){removeErrorsFromArray(sectionID);var checkedElements=$(spamSectionDiv).find('input:checked');if(!checkedElements.length){addErrorToValidationArray({sectionID:sectionID,messageKey:'application.takesurvey.multichoice.required',replacements:[]});return;}},addValidationEvent:function(){var eventElement="input[name='reportAbuseType']";$(eventElement).on('change',function(){var currentSection=$(this).closest("div[id^='SpamQuestionSection_']").attr('id').split('_')[1];validateCurrentSection(currentSection);});}};var text={validate:function(){var textElement=spamSectionDiv.find("input:text");var textValue=textElement.val();if(!isEmpty(textValue)&&!validateEmail(textValue)){addErrorToValidationArray({sectionID:sectionID,messageKey:'application.takesurvey.validation.text.email.failure',replacements:[]});return;}},addValidationEvent:function(){var eventElement=spamSectionDiv.find("input:text");$(eventElement).on('change',function(){var currentSection=$(this).closest("div[id^='SpamQuestionSection_']").attr('id').split('_')[1];validateCurrentSection(currentSection);});}};return execute;})();function validateAndSubmitReport(){var spamSections=[{sectionID:1,required:true,validationType:1,questionType:'M'},{sectionID:2,required:false,validationType:0,questionType:'T',required:false},{sectionID:3,required:false,validationType:2,questionType:'T'}];switch(validateReportAbuse(spamSections)){case 0:$('#spamSubmitBtn').prop('disabled',true);qp_sectionDisplayScript.ajaxSubmitFormObject('shadowedBoxBody','/a/SurveyReportAbuse?mode=add',document.getElementById('spamForm'));return false;break;default:return false;}}